[build]
  publish = "_site"
  command = "yarn run build"

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main']
  customDomain = "booster.zywave.dev"
  renderJavaScript = true

# https://github.com/sw-yx/netlify-plugin-rss/
[[plugins]]
package = "netlify-plugin-rss"
  [plugins.inputs]
  # required configs, customize as needed
  dirToScan = "/blog/posts" # a subfolder to scan. "/" to scan all
  authorName = "Zywave, Inc."
  site_url = "https://booster.zywave.dev"
  title = "Booster Blog RSS Feed"
  rssDescription = "Booster Blog RSS Feed"
  categories = ['Technology', 'Zywave', 'Web Development', 'Design']
  contentSelector = "article"
  publishDateSelector = "time"
  descriptionSelector = "meta[name=description]"

# REDIRECT and HEADERS examples

# Redirect rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[redirects]]
#  from = "/*"
#  to = "/blog/:splat"

# The default HTTP status code is 301, but you can define a different one e.g.
# status = 302

# Headers rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

[[headers]]
  for = "/*"

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Content-Security-Policy = "script-src 'self' blob: unpkg.com cdn.zywave.com identity.netlify.com netlify-cdp-loader.netlify.app https://cdn.heapanalytics.com https://heapanalytics.com 'unsafe-eval' 'unsafe-inline'; style-src 'self' unpkg.com cdn.zywave.com https://heapanalytics.com 'unsafe-inline'; frame-src 'self' app.netlify.com; img-src 'self' https://heapanalytics.com; connect-src 'self' https://heapanalytics.com; font-src 'self' https://heapanalytics.com"


# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# applied on a PER-DEPLOY basis.
