backend:
  name: git-gateway
  repo: Zywave/booster
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: "static/baked-potato/images"
public_folder: "/sausages/images"

collections:
  - name: "application_framework"
    label: "Application framework"
    label_singular: "Application framework page"
    folder: "src/_areas/application-framework"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude ToC", name: "hideToc", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "application_framework_components"
    label: "Application framework / Components"
    label_singular: "component"
    folder: "src/_areas/application-framework/components"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude ToC", name: "hideToc", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "API Schema", name: "api", widget: "string" }
      - { label: "Demo URI", name: "demo", widget: "string" }
      - { label: "Main component name", name: "mainComponentName", widget: "string" }
      - { label: "Included elements", name: "includedElements", widget: "list", default: [] }
  - name: "application_framework_developers"
    label: "Application framework / Developers"
    label_singular: "dev doc"
    folder: "src/_areas/application-framework/developers"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude ToC", name: "hideToc", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    label_singular: "blog post"
    folder: "src/_areas/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Exclude ToC", name: "hideToc", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Collection", name: "collection", widget: "select", options: [ "Design", "Engineering", "Research" ] }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
  - name: "design_system"
    label: "Design system"
    label_singular: "Design system page"
    folder: "src/_areas/design-system"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude ToC", name: "hideToc", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "design_system_components"
    label: "Design system / Components"
    label_singular: "component"
    folder: "src/_areas/design-system/components"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude ToC", name: "hideToc", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "API Schema", name: "api", widget: "string" }
      - { label: "Demo URI", name: "demo", widget: "string" }
      - { label: "Main component name", name: "mainComponentName", widget: "string" }
      - { label: "Included elements", name: "includedElements", widget: "list", default: []}
  - name: "design_system_developers"
    label: "Design system / Developers"
    label_singular: "dev doc"
    folder: "src/_areas/design-system/developers"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude ToC", name: "hideToc", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "design_system_patterns"
    label: "Design system / Patterns"
    label_singular: "Patterns doc"
    folder: "src/_areas/design-system/patterns"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude ToC", name: "hideToc", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "design_system_visuals"
    label: "Design system / Visuals"
    label_singular: "Visuals doc"
    folder: "src/_areas/design-system/visuals"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude ToC", name: "hideToc", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "design_system_voice-and-tone"
    label: "Design system / Voice and Tone"
    label_singular: "Voice and tone doc"
    folder: "src/_areas/design-system/voice-and-tone"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude ToC", name: "hideToc", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    label_singular: "page"
    folder: "src/_pages"
    create: true
    nested:
      depth: 10
      summary: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
    meta: {
      path: { widget: string, label: "Path", index_file: "index" }
    }
