backend:
  name: github
  repo: Zywave/booster
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: "/static/images"
public_folder: "/images"

collections:
  - name: "application_framework"
    label: "Application framework"
    label_singular: "Application framework page"
    folder: "src/_areas/application-framework"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude Table of Contents", name: "hideToc", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Nav Title", name: "navTitle", widget: "string" }

  - name: "application_framework_components"
    label: "Application framework / Components"
    label_singular: "component"
    folder: "src/_areas/application-framework/components"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude Table of Contents", name: "hideToc", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "API Schema", name: "api", widget: "string", required: false }
      - { label: "Demo URI", name: "demo", widget: "string", required: false }
      - { label: "Main component name", name: "mainComponentName", widget: "string", required: false }
      - { label: "Included elements", name: "includedElements", widget: "list", default: [] }
      - { label: "Entry point URI", name: "entryPointURI", widget: "string", required: false }
      - { label: "Nav Title", name: "navTitle", widget: "string" }
      - label: "Status override"
        name: "statusOverride"
        widget: "select"
        multiple: false
        required: false
        options:
          - "stable"
          - "unstable"
          - "deprecated"

  - name: "application_framework_developers"
    label: "Application framework / Developers"
    label_singular: "dev doc"
    folder: "src/_areas/application-framework/developers"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude Table of Contents", name: "hideToc", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Nav Title", name: "navTitle", widget: "string" }

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    label_singular: "blog post"
    folder: "src/_areas/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Type", name: "type", widget: "hidden", default: "blogPost" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Exclude Table of Contents", name: "hideToc", widget: "boolean", default: false, required: false }
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        min: 1
        options:
          - "Design"
          - "Engineering"
          - "Research"
          - "Web Components"
          - "Web"
          - "Meta"
          - "Release Notes"
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "design_system"
    label: "Design system"
    label_singular: "Design system page"
    folder: "src/_areas/design-system"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude Table of Contents", name: "hideToc", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Nav Title", name: "navTitle", widget: "string" }

  - name: "design_system_components"
    label: "Design system / Components"
    label_singular: "component"
    folder: "src/_areas/design-system/components"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude Table of Contents", name: "hideToc", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "API Schema", name: "api", widget: "string", required: false }
      - { label: "Demo URI", name: "demo", widget: "string", required: false }
      - { label: "Main component name", name: "mainComponentName", widget: "string", required: false }
      - { label: "Included elements", name: "includedElements", widget: "list", default: []}
      - { label: "Entry point URI", name: "entryPointURI", widget: "string", required: false }
      - { label: "Nav Title", name: "navTitle", widget: "string" }
      - label: "Status override"
        name: "statusOverride"
        widget: "select"
        multiple: false
        required: false
        options:
          - "stable"
          - "unstable"
          - "deprecated"

  - name: "design_system_developers"
    label: "Design system / Developers"
    label_singular: "dev doc"
    folder: "src/_areas/design-system/developers"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude Table of Contents", name: "hideToc", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Nav Title", name: "navTitle", widget: "string" }

  - name: "design_system_patterns"
    label: "Design system / Patterns"
    label_singular: "Patterns doc"
    folder: "src/_areas/design-system/patterns"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude Table of Contents", name: "hideToc", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Nav Title", name: "navTitle", widget: "string" }

  - name: "design_system_visuals"
    label: "Design system / Visuals"
    label_singular: "Visuals doc"
    folder: "src/_areas/design-system/visuals"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude Table of Contents", name: "hideToc", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Nav Title", name: "navTitle", widget: "string" }

  - name: "design_system_voice-and-tone"
    label: "Design system / Voice and Tone"
    label_singular: "Voice and tone doc"
    folder: "src/_areas/design-system/voice-and-tone"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Exclude Table of Contents", name: "hideToc", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Nav Title", name: "navTitle", widget: "string" }

  - name: "introduction"
    label: "Introduction"
    folder: "src/_areas/introduction"
    create: true
    nested:
      depth: 10
      summary: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Nav Title", name: "navTitle", widget: "string" }
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: "pages"
    label: "Misc. Pages"
    label_singular: "page"
    folder: "src/_pages"
    create: true
    nested:
      depth: 10
      summary: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "documentation" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
