backend:
  name: git-gateway
  repo: Zywave/booster
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: "static/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "design_blog" # Used in routes, e.g., /admin/collections/blog
    label: "Design Blog" # Used in the UI
    folder: "src/pages/blog/design" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: "collection", value: "design"}
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Collection", name: "collection", widget: "hidden", "default": "design"}
  - name: "engineering_blog" # Used in routes, e.g., /admin/collections/blog
    label: "Engineering Blog" # Used in the UI
    folder: "src/pages/blog/engineering" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: "collection", value: "engineering"}
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Collection", name: "collection", widget: "hidden", "default": "engineering"}
  - name: "research_blog" # Used in routes, e.g., /admin/collections/blog
    label: "Research Blog" # Used in the UI
    folder: "src/pages/blog/research" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: "collection", value: "research"}
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Collection", name: "collection", widget: "hidden", "default": "research"}
  - name: "component"
    label: "Component"
    folder: "src/pages"
    path: "{{system}}/components/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "component"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "System", name: "system", widget: "select", options: ["design-system", "application-framework"]}
      - {label: "Package", name: "package", widget: "string"}
      - {label: "Included elements", name: "includedElements", widget: "string", default: "[]"}
      - {label: "Subhead", name: "subhead", widget: "string"}
