name: Alex Recommends

on: pull_request_target

jobs:
  alex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Comment on new PR
      uses: brown-ccv/alex-recommends@v1.2.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        no_binary: true
        pr_only: true
        glob_pattern: "src/**"
        profanity_sureness: 2
